{{- include "srox.init" . -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: central
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "serviceaccount" "central") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "serviceaccount" "central") | nindent 4 }}
imagePullSecrets:
{{- range $secretName := ._rox.imagePullSecrets._names }}
- name: {{ quote $secretName }}
{{- end }}

