{{- include "srox.init" . -}}

{{- if not ._rox.scanner.disable -}}

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "srox.globalResourceName" (list . "stackrox-scanner-psp") }}
  labels:
    {{- include "srox.labels" (list . "clusterrole" "stackrox-scanner-psp") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "clusterrole" "stackrox-scanner-psp") | nindent 4 }}
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ include "srox.globalResourceName" (list . "stackrox-scanner") }}
  verbs:
  - use

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stackrox-scanner-psp
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "rolebinding" "stackrox-scanner-psp") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "rolebinding" "stackrox-scanner-psp") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "srox.globalResourceName" (list . "stackrox-scanner-psp") }}
subjects:
  - kind: ServiceAccount
    name: scanner
    namespace: {{ .Release.Namespace }}

---

apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "srox.globalResourceName" (list . "stackrox-scanner") }}
  labels:
    {{- include "srox.labels" (list . "podsecuritypolicy" "stackrox-scanner") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "podsecuritypolicy" "stackrox-scanner") | nindent 4 }}
spec:
  privileged: false
  allowPrivilegeEscalation: false
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'

{{- if ._rox.env.openshift }}
---

kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: {{ include "srox.globalResourceName" (list . "scanner") }}
  labels:
    {{- include "srox.labels" (list . "securitycontextconstraints" "scanner") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "securitycontextconstraints" "scanner") | nindent 4 }}
    kubernetes.io/description: scanner is the security constraint for the Scanner container
priority: 100
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
  - '*'
users:
  - system:serviceaccount:{{ .Release.Namespace }}:scanner
volumes:
  - '*'
allowHostDirVolumePlugin: false
allowedCapabilities: []
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
defaultAddCapabilities: []
fsGroup:
  type: RunAsAny
readOnlyRootFilesystem: false
requiredDropCapabilities: []
{{ end -}}

{{ end -}}
