# This file contains basic configuration options for all services

centralEndpoint: "central.{{ required "unknown namespace" ._rox._namespace }}:443"
createUpgraderServiceAccount: false

{{- if .Release.IsInstall }}
createSecrets: true
{{- end }}

exposeMonitoring: false

helmManaged: true

imagePullSecrets:
  allowNone: false
  useExisting: []
  useFromDefaultServiceAccount: true

additionalCAs: {}

sensor:
  endpoint: "sensor.{{ required "unknown namespace" ._rox._namespace }}:443"

admissionControl:
  listenOnCreates: false
  listenOnUpdates: false
  listenOnEvents: {{ not ._rox.env.openshift }}
  dynamic:
    enforceOnCreates: false
    scanInline: false
    disableBypass: false
    timeout: 3
    enforceOnUpdates: false

collector:
  collectionMethod: "KERNEL_MODULE"
  disableTaintTolerations: false

---
sensor:
  exposeMonitoring: {{ ._rox.exposeMonitoring }}
collector:
  exposeMonitoring: {{ ._rox.exposeMonitoring }}
admissionControl:
  exposeMonitoring: {{ ._rox.exposeMonitoring }}
