# This file contains the default image (registry + name + tag) settings) for all StackRox Secured Cluster
# Services.

image:
  registry: stackrox.io
  main:
    name: main
    pullPolicy: IfNotPresent
  collector:
    name: collector
---
image:
  main:
    registry: {{ ._rox.image.registry }}
  collector:
    registry: {{ if or (eq ._rox.image.registry "stackrox.io") (eq ._rox.image.registry "registry.connect.redhat.com") }}collector.stackrox.io{{ else }}{{ ._rox.image.registry }}{{ end }}
---
image:
  main:
    repository: {{ list ._rox.image.main.registry ._rox.image.main.name | compact | join "/" }}
  collector:
    repository: {{ list ._rox.image.collector.registry ._rox.image.collector.name | compact | join "/" }}
---
image:
  main:
    {{- if or ._rox.image.main.tag ._rox.image.main.fullRef }}
      {{- include "srox.warn" (list . "You have specified an explicit main image (tag). This will prevent the main image from being updated correctly when upgrading to a newer version of this chart.") }}
    {{- else }}
    _abbrevImageRef: {{ ._rox.image.main.repository }}
    {{- end }}
    tag: {{ .Chart.AppVersion }}
  collector:
    {{- if or ._rox.image.collector.tag ._rox.image.collector.fullRef }}
      {{- include "srox.warn" (list . "You have specified an explicit collector image tag. This will prevent the collector image from being updated correctly when upgrading to a newer version of this chart.") }}
      {{- if ._rox.collector.slimMode }}
        {{- include "srox.warn" (list . "You have specified an explicit collector image tag. The slim collector setting will not have any effect.") }}
      {{- end }}
    {{- else }}
    _abbrevImageRef: {{ ._rox.image.collector.repository }}
    {{- end }}
---
collector:
  slimMode: {{ eq ._rox.image.collector.registry "collector.stackrox.io" }}
---
image:
  collector:
    {{- if ._rox.collector.slimMode }}
    tag: "3.1.15-slim"
    pullPolicy: IfNotPresent
    {{- else }}
    tag: "3.1.15-latest"
    pullPolicy: Always
    {{- end }}
---
image:
  main:
    fullRef: {{ printf "%s:%s" ._rox.image.main.repository ._rox.image.main.tag }}
  collector:
    fullRef: {{ printf "%s:%s" ._rox.image.collector.repository ._rox.image.collector.tag }}
collector:
  imagePullPolicy: {{ ._rox.image.collector.pullPolicy }}
  complianceImagePullPolicy: {{ ._rox.image.main.pullPolicy }}
sensor:
  imagePullPolicy: {{ ._rox.image.main.pullPolicy }}
admissionControl:
  imagePullPolicy: {{ ._rox.image.main.pullPolicy }}
